Add placeholders in config-file settings and config-general-settings page
gedankenstuecke/oh_data_uploader pull request #11
Opened 2018-02-20 05:45 UTC by manaswinidas

Changes are uniform throughout

2018-02-20 16:46 UTC, gedankenstuecke commented
Thanks for this, there are a couple of issues with this: 

1. If you browse to `project-admin/config-file-settings` it will now crash with the following error. This is because the view expects to decode some `json`, which doesn't work because there is now no default metadata attached. See error below

```
Request Method: | GET
-- | --
http://0.0.0.0:5000/project-admin/config-file-settings
2.0.1
JSONDecodeError
Expecting value: line 1 column 1 (char 0)
```

To make this work the corresponding view needs to be extended to make sure it doesn't try to decode the `json` if the field is empty

2. On the main page the project title and description are now absent by default. This yields a rather ugly view before people enter data (see screenshot below). To fix this it would be good if the template could be extended and display some kind of placeholder there as well in case the current project title/description are empty. 

![image](https://user-images.githubusercontent.com/674899/36436914-73cb7b30-161a-11e8-9a81-9f9d65c81a25.png)

Could you do these updates to this pull request? 😄

2018-02-20 16:48 UTC, manaswinidas commented
Sure! I'll do it. Thanks for reviewing.

2018-02-20 16:48 UTC, gedankenstuecke commented
Thanks, looking forward to it!

2018-02-22 06:45 UTC, manaswinidas commented
I have made the changes. Kindly review it.

2018-02-22 16:17 UTC, gedankenstuecke requested changes
Just a minor thing, the templates should also have a default for the `project_description` as we now allow them to be empty. Otherwise good to merge! 👍

2018-02-22 16:17 UTC, gedankenstuecke commented on oh_connection/templates/oh_connection/index.html
>            {{config.project_description}}
It would be great if you could add a `default:` for the `config.project_description` too, as these are now also allowed to be empty. :-)

2018-02-22 16:17 UTC, gedankenstuecke commented on project_admin/views.py
> +    tags = ','.join(json.loads(project_config.file_tags)) if project_config.file_tags else ''
👍 that's a good solution!

2018-02-22 18:18 UTC, manaswinidas commented
I added default for project description. Thanks for reviewing!

2018-02-22 18:21 UTC, gedankenstuecke commented
Ok, now only one thing is missing: You've changed models, so you will need to create the migrations for this. You can do so by `manage.py makemigrations`. Once this is done add the new migration file to the repo and we should be ready to merge!

2018-02-22 18:34 UTC, gedankenstuecke commented
Oh, and the page at `project-admin/config-general-settings` now doesn't have a `placeholder` for the `project title`. Please add one for that too!

2018-02-22 18:53 UTC, manaswinidas commented
Is it okay now?

2018-02-22 18:58 UTC, gedankenstuecke approved these changes
Yes, that's perfect now! Sorry for the back & forth on this one, but I hope you agree that this has improved the overall quality! 🎉

2018-02-22 18:58 UTC, merged

2018-02-22 19:00 UTC, manaswinidas commented
I totally agree! Some issues need to be resolved and every bit has to be taken care of. Thanks for reviewing! I learnt a lot.

2018-02-22 19:08 UTC, gedankenstuecke commented
That's great to hear! I'm glad it was useful to you too!