Tests config_homepage_text
gedankenstuecke/oh_data_uploader pull request #47
Opened 2018-03-03 19:49 UTC by troublemagnet

2018-03-03 22:31 UTC, gedankenstuecke requested changes
That looks good overall! Instead of only testing for the redirect status code please also test the redirect target, both can be done in one go with `self.assertRedirects` (see inline comments)

2018-03-03 22:31 UTC, gedankenstuecke commented on project_admin/tests/tests.py
> +        self.assertEqual(response.status_code, 302)
Please use `self.assertRedirects` to check for redirects. You can use it like this: `self.assertRedirects(response, '/where-does-it-redirect-to/')`

2018-03-03 22:31 UTC, gedankenstuecke commented on project_admin/tests/tests.py
> +        self.assertEqual(response.status_code, 302)
Should also use `self.assertRedirects` as it not only tests the status code but also the target.

2018-03-03 22:31 UTC, gedankenstuecke commented on project_admin/tests/tests.py
> +        self.assertEqual(response.status_code, 302)
`self.assertRedirects`

2018-03-03 22:31 UTC, gedankenstuecke commented on project_admin/tests/tests.py
> +        self.assertEqual(response.status_code, 302)
`self.assertRedirects` :)

2018-03-04 05:56 UTC, troublemagnet commented
@gedankenstuecke Made the changes! Ready for review

2018-03-04 18:48 UTC, gedankenstuecke approved these changes

2018-03-04 18:48 UTC, merged

2018-03-04 18:48 UTC, gedankenstuecke commented
That's great, thanks so much!